spring:
  jpa:
    show-sql: true # sql 콘솔 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL8 sql 변경

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true # h2 데이터베이스 웹 콘솔 접근

server:
  servlet:
    encoding:
      force-response: true # mustache 한글 인코딩 설정(??? 오류 발생시 추가)